### PR TITLE
Fix up vanilla WebGPU code in Loading from File

### PR DESCRIPTION
**Pull request by TheSunCat**

### CODE REVIEW

**Comment by eliemichel** [comment]
👌 thx!

**Comment by TheSunCat** [comment]
Thanks for the guide! Used it to make a rendering framework for a game jam game, and it turned out great.

**Comment by eliemichel** [comment]
Nice! :) Is the outcome of your game jam available on itch or somewhere?

**Comment by TheSunCat** [comment]
Yes!
Itch: https://giallovero.itch.io/wreckage-runner
Source code: https://git.allpurposem.at/mat/Unwrap-2024

It has an issue with performance caused by particles never getting cleared. I wanted to play with instancing but we ran out of time.

I would love to learn webgpu further than what is currently taught in the guide, would you recommend any specific additional resources? Been just looking at JS examples thus far and trying to adapt them to C++.
I also read about a WebGL backend to WebGPU, which would allow a wasm build to run on non-nightly Firefox, but I couldn't find info on enabling it, so there is only a non-web build.

**Pull request merged**
