### PR TITLE
Fix typos + small grammar issues in documentation

### PR DESCRIPTION
**Pull request by suny-am**
- Fix typos
- Fix small grammar issues

PS: Thank you so much for sharing your knowledge! It is deeply appreciated!

### CODE REVIEW

**Comment by eliemichel** [comment]
Thanks a lot! I kind of like my oral-style "okey" but if you tell me you're a native(-enough) English speaker and it feels weird to your eyes then let's fix it!

**Comment by suny-am** [comment]
I actually do like it too! It has a nice feel to it! The softer more spoken style would be "Okay", which might be better in this case if that is the tone you are going for!

**Comment by eliemichel** [comment]
Let's go for "Okay" then :) Do I let you update this PR or do you prefer me to do it?

**Comment by suny-am** [comment]
I would feel bad letting you correct my addition, so I'll do it ASAP! :)

**Pull request merged**
