### PR TITLE
Just a little typo I found.

### PR DESCRIPTION
**Pull request by MiguelVDP**

### CODE REVIEW

**Comment by MiguelVDP** [comment]
Thanks for your work!

**Comment by eliemichel** [comment]
Thanks! :) Feel free to report any other issue

**Comment by MiguelVDP** [comment]
Hi,

Im sorry for troubling, but im trying to implement the c++ wrapper you
facilitate at your guide but I´m always getting the same error when
including it in the project:

[image: imagen.png]
This errors refer to the functions implemented in webgpu.hpp that are
compiled when defined WEBGPU_CPP_IMPLEMENTATION.

Thanks for your time.

**Comment by eliemichel** [comment]
The image got lost :/ Were these "undefined symbol" errors? There has been some discrepancies in the binaries the guide links to in the last days, try with this in your `webgpu/` folder: https://github.com/eliemichel/WebGPU-distribution/tree/wgpu

**Comment by MiguelVDP** [comment]
Thanks a lot!

It seems I had a deprecated version of the webgpu.hpp file so the problem
got solved once I updated it 😁.

By the way, I am actually working on a project consisting of implementing a
physics simulator sistem using WebGPU, I was wondering if you guys know of
any discord server or community-like place where I could find some guidance.

Thanks again for your time.

**Comment by eliemichel** [comment]
Since you're not the first to ask, I decided open a Discord server around the guide :) https://discord.gg/xwP3GD5S

**Comment by MarcosDanielTorres** [comment]
> Since you're not the first to ask, I decided open a Discord server around the guide :) https://discord.gg/xwP3GD5S

First of all, thank you for your work. 
I tried the link but it expired :( If you have the time, would you be so kind to send the invite again?

**Comment by eliemichel** [comment]
Here is one that should be permanent! https://discord.gg/2Tar4Kt564

**Pull request merged**
